unsplash/intlc

.gitignore, .golden/e2e/example/golden.ts, intlc.cabal, test/Intlc/EndToEndSpec.hs
Closes #35. Thanks @Magellol for your initial outlay!
This PR adds golden/snapshot testing with an example test migration included. There's no longer any need to write the expected output code, merely verify prior to committing that it looks correct.
It outputs `.ts` files, so we get syntax highlighting and per @Magellol's suggestion in the linked issue we could pursue typechecking these perhaps as a CI step. If a test fails the output will be the printed error(s).
I believe the gitignore pattern is safe provided we always include an `actual` prefix in our `actualFile` outputs.
=> Add golden/snapshot testing

lib/Intlc/Parser.hs, test/Intlc/ParserSpec.hs
Closes #24.
Per the tests, parsing is now much stricter around interpolations; the likes of `{unclosed` and `{x, badtype}` are no longer parseable. The rationale is that the translator can always incorporate braces by escaping, and this strictness makes it a lot easier to spot faulty messages.
Is there any reason we can't or shouldn't rely upon escaping like this for access to braces?
=> Strict braces

lib/Intlc/Parser.hs, test/Intlc/EndToEndSpec.hs
Closes #14.
This PR performs cheap validation against message keys to ensure all characters are either alphabetical or underscores.
A better long-term solution would probably be to have per-compiler massaging of keys, and error handling to handle conflicts in that scenario, but for now with only TS(X) backends this does the job.
Numbers aren't permitted as they aren't valid as the first character of a JS identifier, and I want this code to be as simple as possible at this stage. `$` isn't permitted because I don't want to encourage JS looking like PHP. In all seriousness, that could be fixed with the above per-compiler approach, but I think this is reasonable as a short-term solution to ensure valid output.
=> Validate keys contain only valid chars

.golden/e2e/example/golden.ts, lib/Intlc/Backend/JavaScript/Compiler.hs, lib/Intlc/Backend/TypeScript/Compiler.hs, lib/Intlc/Compiler.hs, test/Intlc/EndToEndSpec.hs
Only prepend a react import once when there is at least one TSX backend
Again, this may not be idiomatic haskell 😅
=> Optionally prepend react import if there is at least one TSX backend

lib/Intlc/Parser.hs, test/Intlc/ParserSpec.hs
Fixes #65.
We have a recursive token parser. Previously to support `#` we tacked support on inside the plural parser with `<|>`. This worked for shallow usages, but not for nested/deep usages in which we'd recurse back around to the aforementioned token parser sans `#` support.
We now instead keep track of plural `State`. When we encounter `#` in that top-level token parser, we inspect what plural context we're in. If we're in one, we parse as an interpolation. If we're not, we fail/skip the parse leading to it parsing as plaintext.
In order to support `State` in our `Parser`, we now use the `ParsecT` type where the `T` stands for "transformer". The previously used `Parsec` type was a mere alias around this with the `Identity` monad instead of our `State` monad, hence how little code …
=> Fix nested plural hash

lib/Intlc/Backend/JavaScript/Compiler.hs, lib/Intlc/Compiler.hs, lib/Intlc/Core.hs, lib/Intlc/Parser.hs
Not a ton of thought put into this, a quick fix to unblock. Note that absent description keys will be output as `"description": null`.
=> Preserve "description" key when flattening

lib/Intlc/Backend/JavaScript/Compiler.hs, lib/Intlc/Compiler.hs, test/Intlc/CompilerSpec.hs, test/Intlc/EndToEndSpec.hs
Fixes #78.
Some refactoring is probably warranted so that `Intlc.Compiler` becomes agnostic to our compilers, and `Intlc.Backend.JavaScript.Compiler` itself would become responsible for things like this and the React import. But that's not a priority whilst we only use TS(X) output. :see_no_evil:
=> Output a valid JS module when compiled output is empty

.golden/e2e/example/golden.ts, lib/Intlc/Backend/JavaScript/Compiler.hs, test/Intlc/EndToEndSpec.hs
Fixes #83. See commit message for rationale.
Alongside the removal of single quotes visible in the diff, the core issue addressed is as follows.
Given `{ "foo": { "backend": "tsx", "message": "bar" } }`...
Before: `export const foo: () => ReactElement = () => 'bar'`
After: `export const foo: () => ReactElement = () => <>bar</>`
This also makes #82 a substantially lesser bug given how much more rarely used a backtick is in copy.
=> Fix TSX backend output when there are no interpolations

cli/Main.hs, lib/Intlc/Backend/JavaScript/Compiler.hs, lib/Intlc/Backend/TypeScript/Compiler.hs, lib/Intlc/Compiler.hs, lib/Intlc/Parser.hs, test/Intlc/CompilerSpec.hs, test/Intlc/EndToEndSpec.hs
This PR principally fixes #81, however it also checks that keys aren't empty, and improves extensibility for any future backends that have different identifier rules than JavaScript/TypeScript.
Example compile output:
```
Invalid keys:
[Empty identifier found.]
bad key 1: invalid identifier.
delete: reserved word.
```
=> Improved key validation: Emptiness, reserved words, and beyond JavaScript

lib/Intlc/Compiler.hs
Fixes #104.
Another reason I don't love how flattening is implemented is that this was missed without warning.
Test case:
```
before {myBoolean, boolean, true {true} false {false}} {myVar, select, a {a} b {b}} after
```
Before:
```
{myVar, select, a {before {myBoolean, boolean, true {true} false {false}} a after} b {before {myBoolean, boolean, true {true} false {false}} b after}}
```
After:
```
{myBoolean, boolean, true {{myVar, select, a {before true a after} b {before true b after}}} false {{myVar, select, a {before false a after} b {before false b after}}}}
```
=> Fix booleans not being flattened

intlc.cabal, lib/Intlc/Parser.hs
Closes #113, though I'd still like to improve the story around line numbers and such.
Given:
```json
{
"f": {
"message": "{x, bad1}"
},
"g": {
"message": "{y, bad2}"
}
}
```
Before:
```console
$ intlc compile <file> -l <locale>
f:1:5:
|
1 | {x, bad1}
|     ^^^^^
unexpected "bad1}"
expecting "boolean", "date", "number", "plural", "select", "selectordinal", "time", or white space
```
After:
```console
$ intlc compile <file> -l <locale>
f:1:5:
|
1 | {x, bad1}
|     ^^^^^
unexpected "bad1}"
expecting "boolean", "date", "number", "plural", "select", "selectordinal", "time", or white space
g:1:5:
|
1 | {y, bad2}
|     ^^^^^
unexpected "bad2}"
expecting "boolean", "date", "number", "plural", "select", "selectordinal", "time", or white space
```
=> Report all dataset parse failures

lib/Intlc/Backend/ICU/Compiler.hs, lib/Intlc/Backend/JavaScript/Language.hs, lib/Intlc/Backend/TypeScript/Compiler.hs, lib/Intlc/Backend/TypeScript/Language.hs, lib/Intlc/Compiler.hs, lib/Intlc/ICU.hs, lib/Intlc/Parser/ICU.hs, test/Intlc/Backend/TypeScriptSpec.hs, test/Intlc/CompilerSpec.hs, test/Intlc/Parser/ICUSpec.hs
This had been bugging me for a while and came up when talking to @Magellol.
`ICU.Message` was a sum type (`Static | Dynamic`) and is now a newtype holding a `Stream`. `NEStream` (non-empty `Stream`) is removed. There was only one part of the codebase that cared about whether the message was static or not, the TypeScript compiler as it pertains to the argument (`x` or `()`), and that's trivially replaced with a quick `any` call.
`ICU.Arg` was essentially just an additional wrapper around `ICU.Interpolation`'s data (name and type).
=> Slim the AST a bit

ARCHITECTURE.md, cli/Main.hs, intlc.cabal, lib/Intlc/Backend/ICU/Compiler.hs, lib/Intlc/Backend/JSON/Compiler.hs, lib/Intlc/Backend/JavaScript/Language.hs, lib/Intlc/Compiler.hs, lib/Intlc/Core.hs, test/Intlc/CompilerSpec.hs
Aeson decoding of JSON was replaced in #115. This PR is the equivalent for encoding/compiling. This frees us from Aeson's constraints such as an inability to produce non-minified output, however that can be addressed in another PR. As with the parsing, the replacement code is very small as we only need to know how to compile a single type.
=> Add JSON compiler

internal/CLI.hs, internal/Main.hs, lib/Intlc/Compiler.hs, lib/Intlc/ICU.hs, test/Intlc/CompilerSpec.hs, test/Intlc/EndToEndSpec.hs
Closes #138.
Adds plural expansion to the internal CLI, operating via stdin and stdout to make its use prior to zipping comfortable. Because we only expand plurals with a wildcard, this should never result in a different compiled type signature (`other`/wildcard means widened `number` as opposed to literals), and as such we shouldn't need to apply this to our own master English translations. This means we do not add plural forms for a literal plural like `{n, plural, =0 {x} =1 {y}}` (which compiles to `n: 0 | 1`), but I don't think we use these much. Plural expansion applies to both `plural` and `selectordinal`, which each fall under the `Plural` type in our AST.
```console
$ echo '{"f":{"message": "You have {n, plural, one {cat} other {cats}}!"}}' | intlc-internal expand-plurals …
```
=> Add plural expansion

lib/Intlc/Backend/ICU/Compiler.hs
Fixes #97.
Given via `intlc flatten`:
```json
{
"f": {
"message": "{n, plural, =1 {}}"
}
}
```
Before:
```
{"f":{"message":"{n, plural, =1 {} }","backend":"ts","description":null}}
```
After:
```
{"f":{"message":"{n, plural, =1 {}}","backend":"ts","description":null}}
```
---
I'm going to be lazy and not add a test for this on the basis that:
1. It's not a major bug if it happens again.
2. Testing is tracked as part of a larger issue at #49, sort of.
3. Testing is _really_ implicitly tracked by #129 which will presumably rely upon this very ICU compiler.
=> Fix dangling space in ICU compiler literal plural output

.github/workflows/check.yml
This reverts commit bf6bc0c206f794e34d17b71d5c0cef71a72b0843.
It seems to be working again. /shrug
Closes #151.
=> Revert "Disable CI formatting"

lib/Intlc/Backend/ICU/Compiler.hs, lib/Intlc/Backend/JavaScript/Language.hs, lib/Intlc/Backend/TypeScript/Language.hs, lib/Intlc/Compiler.hs, lib/Intlc/ICU.hs, lib/Intlc/Parser/ICU.hs, test/Intlc/Backend/TypeScriptSpec.hs, test/Intlc/CompilerSpec.hs, test/Intlc/LinterSpec.hs, test/Intlc/Parser/ICUSpec.hs
Closes #108. #136 will follow in another PR.
Given:
```json
{
"f": { "message": "{n, plural, other {}}" },
"g": { "message": "{n, selectordinal, other {}}" },
}
```
Previously:
```console
$ intlc compile -l foo ./bar.json
./bar.json:2:34:
|
2 |   "f": { "message": "{n, plural, other {}}" },
|                                  ^^^^
unexpected "othe"
expecting "few", "many", "one", "two", "zero", '=', or white space
./bar.json:3:41:
|
3 |   "g": { "message": "{n, selectordinal, other {}}" },
|                                         ^^^^
unexpected "othe"
expecting "few", "many", "one", "two", "zero", '=', or white space
```
Now:
```console
$ intlc compile -l foo ./bar.json
export const f: (x: { n: number }) => string = x => `${(() => { switch (x.n as typeof x.n) {  default: return ``; } …
```
=>  Allow plural lone wildcard

lib/Intlc/Linter.hs, test/Intlc/LinterSpec.hs
=> Lint against lone plural wildcard

.github/workflows/check.yml, .github/workflows/publish.yml, README.md, flake.lock, flake.nix, intlc.cabal
Replaces #167. This PR _should_:
- Ensure that all platforms can get GHC, Cabal, etc without any building necessary i.e. binaries should already be cached and fetched from Hydra CI. I suspect we could still get away with changing the GHC version a bit more liberally but let's leave that for today.
- Add HLS to the dev shell, but not for M1 Macs specifically for which it's still marked as broken. For these users HLS can still be sourced from the likes of ghcup. (Please check that the HLS you have is compatible with GHC 9.0.2!)
The issue with GHC 9.x and ghcup referenced in #162 should now be resolved.
=> Conditionally add HLS to dev shell & GHC 9.0.2

intlc.cabal, lib/Intlc/Backend/ICU/Compiler.hs, lib/Intlc/Backend/JavaScript/Compiler.hs, lib/Intlc/Backend/JavaScript/Language.hs, lib/Intlc/Backend/TypeScript/Compiler.hs, lib/Intlc/Backend/TypeScript/Language.hs, lib/Intlc/Compiler.hs, lib/Intlc/ICU.hs, lib/Intlc/Linter.hs, lib/Intlc/Parser/ICU.hs, test/Intlc/Backend/TypeScriptSpec.hs, test/Intlc/CompilerSpec.hs, test/Intlc/ICUSpec.hs, test/Intlc/LinterSpec.hs, test/Intlc/Parser/ICUSpec.hs, test/Intlc/Parser/JSONSpec.hs
Rather than our `Node` constructors containing `[Node]`, they now contain `Node` in those places, and an additional `Node` sibling. In a sense this is directly embedding Haskell's singly-linked list into our core AST type, hence the addition of the `Fin` constructor, equivalent to list `Nil`. Alternative primed constructors are supplied via patterns, so instead of `String x Fin` you can write `String' x`.
With this PR alone it's a relatively neutral change, but it enables more powerful recursion schemes in #171.
Additionally an `IsString` instance has been added, which can be backported to the previous AST representation if this PR isn't merged. It transforms `"xy"` directly into `Char 'x' (Char 'y' Fin)` (previously `Plaintext "xy"`).
Oh, and with us embracing holding chars rather than …
=> Embed list directly into AST type

intlc.cabal, lib/Intlc/Backend/ICU/Compiler.hs, lib/Intlc/Backend/JavaScript/Language.hs, lib/Intlc/Backend/TypeScript/Language.hs, lib/Intlc/Compiler.hs, lib/Intlc/ICU.hs, lib/Intlc/Linter.hs, test/Intlc/LinterSpec.hs
Requires #170, else the catamorphism can no longer handle recursion in its entirety. Closes #48.
This is a pretty substantial PR conceptually. Aside from being fun and interesting, I think it also makes bugs like #101 less likely. Recursion schemes enable us to no longer explicitly recurse and instead, in the case of catamorphisms, merely handle the gathered data at each layer. It's essentially abstracting out the explicit act of recursing, so instead of in that sense saying how data will be transformed, we instead say what we'll do with said data.
`NodeF a` is a pattern functor rewrite of `Node`. Wherever `Node` references itself recursively, the recursive references are replaced with a reference to type argument `a`. This allows us to derive base typeclass instances like `Functor` and, …
=> Add pattern functor and utilise recursion schemes/catamorphisms

README.md, cli/CLI.hs, cli/Main.hs, intlc.cabal, lib/Intlc/Backend/ICU/Compiler.hs, lib/Intlc/Backend/JSON/Compiler.hs, lib/Intlc/Parser.hs, lib/Intlc/Parser/ICU.hs, lib/Intlc/Prettify.hs, test/Intlc/EndToEndSpec.hs, test/Intlc/PrettifySpec.hs
Closes #129. For now the text content must be supplied as per the example instead of via stdin; a change here could be covered by #110.
```console
$ cat x.json
{
"x": {
"message": "{hasTags, boolean, true {{type, select, overLimit {{upperLimit, number}+ best free {formattedListOfTags} photos on Unsplash} belowLimit {{photoTotal, number} best free {formattedListOfTags} photos on Unsplash}}} false {{type, select, overLimit {{upperLimit, number}+ best free photos on Unsplash} belowLimit {{photoTotal, number} best free photos on Unsplash}}}} {another, select, a {{foo}} b {bar}}"
}
}
$ intlc prettify $(cat x.json | jq -r .x.message)
{hasTags, boolean, 
true {{type, select, 
overLimit {{upperLimit, number}+ best free {formattedListOfTags} photos on Unsplash}
belowLimit {{photoTotal, number} …
```
=> Add ICU prettifier

README.md, cli/Main.hs, internal/Main.hs, intlc.cabal, lib/Intlc/Backend/JSON/Compiler.hs, lib/Intlc/Backend/JavaScript/Compiler.hs, lib/Intlc/Compiler.hs, lib/Intlc/Core.hs, lib/Intlc/ICU.hs, lib/Intlc/Linter.hs, lib/Intlc/Parser.hs, lib/Intlc/Parser/ICU.hs, lib/Intlc/Parser/JSON.hs, test/Intlc/EndToEndSpec.hs, test/Intlc/LinterSpec.hs, test/Intlc/Parser/ICUSpec.hs, test/Intlc/Parser/JSONSpec.hs
There's some further minor refactoring that could be done but this PR is already fairly big, particularly conceptually, and I'm really happy with where it's at as-is.
This PR adds a mechanism by which we can record AST source annotations/offsets during parsing for later use, and utilises them to drastically improve linting output. Closes #142.
Given:
```json
{
"msg": {
"message": "Some words {mySelect, select, other {}} {myCardinal, plural, =1 {} =1 {}}"
}
}
```
Before:
```
msg: 
Redundant select: mySelect
Duplicate plural case: myCardinal, =1
```
With this PR:
```
translations.json:3:29:
|
3 |     "message": "Some words {mySelect, select, other {}} {myCardinal, plural, =1 {} =1 {}}"
|                             ^^^^^^^^
redundant-select: Select named `mySelect` is redundant as it only …
```
=> AST annotations and fancy lint errors

README.md, cli/CLI.hs, cli/Main.hs, internal/CLI.hs, internal/Main.hs, lib/Intlc/Backend/JSON/Compiler.hs, lib/Intlc/Compiler.hs, test/Intlc/CompilerSpec.hs
This PR adds a `--minify` flag anywhere we're outputting JSON, and absent that - by default - outputs prettified JSON.
The formatting logic is mostly copied from the prettify module (which prettifies ICU for `intlc prettify`). As there prettified output uses tabs for indentation.
Example:
```console
$ cat x.json
{
"x": { "message": "Hello {name}" },
"y": { "message": "Today is a {day, select, Friday {glorious} other {fine}} day." },
}
$ intlc flatten x.json
{
"x": {
"message": "Hello {name}",
"backend": "ts",
"description": null
},
"y": {
"message": "{day, select, Friday {Today is a glorious day.} other {Today is a fine day.}}",
"backend": "ts",
"description": null
}
}
$ intlc flatten x.json --minify
{"x":{"message":"Hello {name}","backend":"ts","description":null},"y":{"message":"{day, …
```
=> Prettified JSON

cli/CLI.hs, intlc.cabal
Closes #98.
Follows the [CLIG](https://clig.dev/#arguments-and-flags) idiom/suggestion of `--version`.
Uses Git to produce the output so it can't fall out of date. Ideally it'd conditionally append "-dirty" as well, but that's not currently supported by the library and my own attempt was flaky.
```console
$ git switch version-opt
$ cabal run -- intlc --version
v0.7.0-12-g8624452
$ git tag v0.8.0
$ cabal clean # Cabal doesn't know we need to rebuild. Naturally won't be an issue in CI.
$ cabal run -- intlc --version
v0.8.0
$ touch foo && git add foo && git commit
$ cabal clean
$ cabal run -- intlc --version
v0.8.0-1-g06fd894
```
=> Add --version option

CHANGELOG.md, cli/CLI.hs, cli/Main.hs, intlc.cabal, lib/Intlc/Backend/ICU/Compiler.hs, lib/Intlc/Backend/JSON/Compiler.hs, lib/Intlc/Prettify.hs, lib/Intlc/Printer.hs, test/Intlc/CompilerSpec.hs, test/Intlc/PrettifySpec.hs
Closes #194. Once this is merged I'll release 0.8.
```console
$ cat x.json
{
"x": { "message": "Hello {name}" },
"y": { "message": "Today is a {day, select, Friday {glorious} other {fine}} day." },
}
$ # Default behaviour is unchanged, we still print tabs.
$ intlc flatten x.json
{
"x": {
"message": "Hello {name}",
"backend": "ts",
"description": null
},
"y": {
"message": "{day, select, Friday {Today is a glorious day.} other {Today is a fine day.}}",
"backend": "ts",
"description": null
}
}
$ # Minification is likewise unchanged, even in the presence of --indent.
$ intlc flatten --minify --indent 4 x.json
{"x":{"message":"Hello {name}","backend":"ts","description":null},"y":{"message":"{day, select, Friday {Today is a glorious day.} other {Today is a fine …
```
=> Add --indent option

lib/Intlc/Compiler.hs, test/Intlc/CompilerSpec.hs
Should fix #199
I took the aggressive approach described in #199.
I ran it on our set of translation files and it didn't change anything except for two files that were correctly fixed :)
I left a comment to explain the Callback branch as a lot happen in a single line.
There might be some issues with formatting and general Haskell conventions.
=> Flatten callback nodes

.github/actions/cabal-cache/action.yml, .github/workflows/check.yml, .github/workflows/publish.yml, flake.nix
This PR fixes the Cabal store cache, adds cache restore keys, splits TypeScript dependencies into their own Nix shell, and adds caching of incremental build artifacts.
Building is reduced from ~5 mins to ~1 min 30s. A CI run with changed code and dependencies should be expected to run somewhere between these two numbers, utilising partial caches. The TypeScript typechecking job is also reduced from ~60s to ~20s
=> Better CI caching

.github/workflows/publish.yml
Ref: https://github.com/softprops/action-gh-release/issues/400
It looks like this is required now due to a change in github's defaults https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
Here's a failed job described in the issue: https://github.com/unsplash/intlc/actions/runs/8800916562/job/24153469892
=> Add write permission to publish workflow

.github/workflows/publish.yml
This _should_ work but being a "larger" runner it'll incur a small cost. Worth it to avoid wasted developer time.
Closes #188 as there's currently no demand for other OS/arch pairs.
Once merged I'll release 0.8.3 to test it. If it doesn't work I'll mess with master until it does, so this PR is mainly for visibility. 😛
=> Publish/build macos-aarch64 in CI
